"""create project table

Revision ID: 06e44afe52ff
Revises: ca5d4242b3a7
Create Date: 2024-05-29 11:57:26.831001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e44afe52ff'
down_revision: Union[str, None] = 'ca5d4242b3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description_inital', sa.String(length=300), nullable=True),
    sa.Column('image1', sa.String(length=100), nullable=True),
    sa.Column('image2', sa.String(length=100), nullable=True),
    sa.Column('image3', sa.String(length=100), nullable=True),
    sa.Column('description_finish', sa.String(length=300), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_data'), 'projects', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_data'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
