"""create are,doubt table

Revision ID: bacda5c6ecd8
Revises: 06e44afe52ff
Create Date: 2024-05-29 12:31:39.423109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bacda5c6ecd8'
down_revision: Union[str, None] = '06e44afe52ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doubts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['id_area'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doubts')
    op.drop_table('areas')
    # ### end Alembic commands ###
